# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 282ed65704c920e51fd3997e95a1fe949cf78c37288a25db6606824865bf5ec387a7cf54e7e90573d033d655ede46e26646bca04530e6c921e76d4d397631937

test:
  secret_key_base: cb2f6f49ef95330e6ea1e99d7c3ec54bebde76a6a3e168b6544aeb2c38e3a6cdf0804ed8c638baad21c4f5a244ead7fbb082283cd2f83fca715be3c98cd0b4c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
